Expose the result message in case of an SSH authentication error
Not only expose the error message, but also the result message from
calling SSH which contains details about the cause. At the example of
using the wrong SSH key for authentication, with this the console shows

    download check: exit status 255: Permission denied (publickey).

instead of just

    download check: exit status 255

and the log shows

    trace git-lfs: ssh: download with url failed,
    error: exit status 255, message: Permission denied (publickey).

instead of just

    trace git-lfs: ssh: download attempted with url.
    Error: exit status 255


Former-commit-id: eb855bad0df653345977da600ecef53b9466f49a